---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 86400

# Install docker-py package
- name: Install docker-py package (apt)
  ansible.builtin.apt:
    name: "{{ proxy_docker_py_pkg }}"
    state: present
  when: proxy_docker_py_install
  tags: setup

# Install fail2ban
- name: Install fail2ban (apt)
  ansible.builtin.apt:
    name: "fail2ban"
    state: present
  when: proxy_fail2ban_setup
  tags: fail2ban
